### PR TITLE
Update to pharo70

### PR DESCRIPTION
**Pull request by carolahp**
Espell version updated. 
This version runs in Pharo70

### CODE REVIEW

**Comment by guillep** [comment]
It seems these commits were already there... This means we should probably generate an image and put it in the releases in this repo. Should we?

**Comment by carolahp** [comment]
Yes we should, unless we decide to move it to a repo under a pharo-project account.
Who has access to that account? After we generate the image we must remember to update the reference in https://github.com/pharo-project/pharo/pull/4558#pullrequestreview-294828411

**Comment by guillep** [comment]
> Yes we should, unless we decide to move it to a repo under a pharo-project account.

It does not really matter. We can transfer the repository in its entirety, with releases, issues and PRs.

> Who has access to that account?

I do

> After we generate the image we must remember to update the reference in [pharo-project/pharo#4558 (review)](https://github.com/pharo-project/pharo/pull/4558#pullrequestreview-294828411)

Let's do a todo list.
1- The first point you've already done it in your repo, don't you. I can just upload that file into my this repo.
2- I can do the transfer
3- Once I'm done with that, could you make that pull request?

**Comment by carolahp** [comment]
> Let's do a todo list.
> 1- The first point you've already done it in your repo, don't you. I can just upload that file into my this repo.

Yes, the file is [here](https://github.com/carolahp/PharoBootstrap/releases/tag/v2.0.2) so you can upload it  
> 2- I can do the transfer

Ok

> 3- Once I'm done with that, could you make that pull request?

Of course, I will be waiting then

**Pull request merged**
